const svg = d3.select("svg");
var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
  return new bootstrap.Tooltip(tooltipTriggerEl)
})

const data = [{"id":"goldman","start":"6/2008","end":"12/2019","excerpt":"Last position: Global Head of Credit, Mortgages and Municipal Bonds","label":"Goldman Sachs","section":"Employment","parent":"Employment","type":"event"},
{"id":"reverence","start":"03/2020","end":"null","excerpt":"Partner and CIO","label":"Reverence Capital Partners","section":"Employment","parent":"Employment","type":"event"},
{"id":"PCCECC_apr2007","start":"04/2007","end":"null","excerpt":"In April 2007, Performance Credit Corporation, a financing services provider, andECC Capital Corporation, a real estate investment trust, sued EMC Mortgage Corporation and Bear Stearns Residential Mortgage Corporation in federal court in Santa Ana, California, alleging that the defendants breached a mortgage loan purchase and interim servicing agreement as well as an asset purchase agreement, according to court records (also attached).","label":"null","section":"Litigation","parent":"deposed","type":"event"},
{"id":"PCCECC_jan2009","start":"01/2009","end":"null","excerpt":"He had previously been scheduled to be deposed in January 2009","label":"null","section":"Litigation","parent":"deposed","type":"event"},
{"id":"PCCECC_may2009","start":"05/2009","end":"null","excerpt":"Although not named as a party in the litigation, Verschleiser, a former employee of Bear Stearns, was scheduled to be deposed in May 2009.","label":"null","section":"Litigation","parent":"deposed","type":"event"},
{"id":"PCCECC_aug2009","start":"08/2009","end":"null","excerpt":"In August 2009, the case was dismissed with prejudice.","label":"null","section":"Litigation","parent":"deposed","type":"event"},
{"id":"FHLC_apr2011","start":"04/2011","end":"null","excerpt":"In April 2011, Federal Home Loan Bank of Boston sued Ally Financial, Inc.,Bank of America Corporation, various Bear Stearns affiliates and others in Suffolk County Superior Court in Massachusetts for the alleged sale of mortgage-backed securities by means of “untrue” and “misleading” documents, according to court records (also attached).","label":"null","section":"Litigation","parent":"deposed","type":"event"},
{"id":"FHLC_dec2020","start":"12/2020","end":"null","excerpt":"In February 2017, the case was remanded to the above state court, where it was voluntarily dismissed with prejudice and without costs in December 2020.","label":"null","section":"Litigation","parent":"deposed","type":"event"},
{"id":"FHLC_feb2017","start":"02/2017","end":"null","excerpt":"In February 2017, the case was remanded to the above state court, where it was voluntarily dismissed with prejudice and without costs in December 2020.","label":"null","section":"Litigation","parent":"deposed","type":"event"},
{"id":"FHLC_oct2011","start":"10/2011","end":"null","excerpt":"In October 2011, although not named as a party, Verschleiser gave a deposition in his capacity as a former Bear Stearns employee.","label":"null","section":"Litigation","parent":"deposed","type":"event"},
{"id":"bearstearns_jul2012","start":"07/2012","end":"null","excerpt":"In July 2012, Bear Stearns Mortgage Funding Trust 2006-SL1 sued EMCMortgage LLC and JPMorgan Chase Bank, N.A. in the Delaware Court of Chancery, alleging that the defendants breached certain contracts governing mortgage-backed securities issued by Bear Stearns, according to court records (Attachment 4).","label":"null","section":"Litigation","parent":"deposed","type":"event"},
{"id":"bearstearns_oct2015","start":"10/2015","end":"null","excerpt":"Although not named as a party in the litigation, in October 2015, Verschleiser, a former employee of Bear Stearns, was scheduled to be deposed in the case.","label":"null","section":"Litigation","parent":"deposed","type":"event"},
{"id":"bearstearns_aug2016","start":"08/2016","end":"null","excerpt":"In August 2016, the lawsuit was dismissed without prejudice.","label":"null","section":"Litigation","parent":"deposed","type":"event"},
{"id":"ambac_feb2011","start":"02/2011","end":"null","excerpt":"In February 2011 and March 2012, Ambac Assurance Corporation, then one of the largest insurers of mortgage-backed securities, filed two separate lawsuits against EMC Mortgage LLC (formerly EMC Mortgage Corporation) as well as affiliates of JPMorgan (which acquired Bear Stearns in 2008) in New York County Supreme Court in New York, according to court records (Attachment 5).","label":"null","section":"Litigation","parent":"ambac","type":"event"},
{"id":"ambac_mar2012","start":"03/2012","end":"null","excerpt":"In February 2011 and March 2012, Ambac Assurance Corporation, then one of the largest insurers of mortgage-backed securities, filed two separate lawsuits against EMC Mortgage LLC (formerly EMC Mortgage Corporation) as well as affiliates of JPMorgan (which acquired Bear Stearns in 2008) in New York County Supreme Court in New York, according to court records (Attachment 5).","label":"null","section":"Litigation","parent":"ambac","type":"event"},
{"id":"ambac_jan2016","start":"01/2016","end":"null","excerpt":"In January 2016, JPMorganChase & Co., which had acquired the assets of Bear Stearns, agreed to pay $995 million to settle both of the above lawsuits, according to the articles, and that same month, both cases were discontinued with prejudice.","label":"null","section":"Litigation","parent":"ambac","type":"event"},
{"id":"sued_aug2008","start":"08/2008","end":"null","excerpt":"In August 2008, several health and pension funds and retirement systems filed a class-action lawsuit against Bear Stearns Mortgage Funding Trust 2006-AR1, Structured Asset Mortgage Investments II, Inc., Verschleiser and others in New York County Supreme Court in New York for alleged securities violations, according to court records (Attachment 6).","label":"null","section":"Litigation","parent":"sued","type":"event"},
{"id":"sued_feb2009","start":"02/2009","end":"null","excerpt":"In February 2015, the parties in the lead case reached a $500million settlement, and in May 2015, the case was closed.","label":"null","section":"Litigation","parent":"sued","type":"event"},
{"id":"sued_apr2011","start":"04/2011","end":"null","excerpt":"In April 2011, Massachusetts Mutual Life Insurance Company (“MassMutual”)sued several affiliates of JPMorgan, EMC Mortgage, Washington Mutual and Bear Stearns and certain of the companies’ employees, including Verschleiser, in federal court in Springfield, Massachusetts, according to court records (Attachment 8).","label":"null","section":"Litigation","parent":"sued","type":"event"},
{"id":"sued_sep2011","start":"09/2011","end":"null","excerpt":"In September 2011, the Federal Housing Finance Agency (“FHFA”) sued several financial institutions and companies – including affiliates of JPMorgan, EMC Mortgage and Bear Stearns – and certain of their employees, including Verschleiser, in federal court in Manhattan, New York for alleged securities fraud, according to court records (Attachment 9).","label":"null","section":"Litigation","parent":"sued","type":"event"},
{"id":"sued_dec2011","start":"12/2011","end":"null","excerpt":"In December 2011, Stichting Pensioenfonds ABP (“Stichting”), a pension fund for government and education employees in the Netherlands, sued several financial institutions and companies – including affiliates of JPMorgan, EMC Mortgage and Bear Stearns – and certain of their employees, including Verschleiser, in New York County Supreme Court in New York, according to court records (Attachment 10).","label":"null","section":"Litigation","parent":"sued","type":"event"},
{"id":"sued_jan2012","start":"01/2012","end":"null","excerpt":"In January 2012, John Hancock Life Insurance Company and its affiliates sued several financial institutions and companies – including affiliates of JPMorgan, EMC Mortgage and Bear Stearns – and certain of their employees, including Verschleiser, in New York County Supreme Court in New York, according to court records (Attachment 11).","label":"null","section":"Litigation","parent":"sued","type":"event"},
{"id":"possiblysued_aug2009","start":"08/2009","end":"","excerpt":"In August 2009, Verschleiser and other “wealthy” Aspen homeowners were criticized in news articles for using threats of litigation to block a real estate deal for the sale of the Silver Lining Ranch, a retreat for terminally ill children in the area, to the Aspen Chabad Jewish Community Center (Attachment 12).","label":"null","section":"Litigation","parent":"possiblysued","type":"event"},
{"id":"gscriticized_2012-13","start":"2012","end":"2013","excerpt":"Following the publication of the above mentioned lawsuits naming Verschleiser and involving Bear Stearns, in 2012 and 2013, numerous news articles, blog posts and other online publications criticized Verschleiser and Goldman Sachs for hiring him","label":"null","section":"Press","parent":"Press","type":"event"},
{"id":"batmitzvah_jan2012","start":"01/2012","end":"null","excerpt":"In January 2012, Verschleiser faced criticism from news outlets after paying between $500,000 and $1 million to rent out all 94 rooms of the Hotel Jerome in Aspen, Colorado for a weekend to host his daughter’s bat mitzvah celebration","label":"null","section":"Press","parent":"Press","type":"event"}];

// Assign tooltip classes to ids so bootstrap can register them as tooltips, using the title attribute for the content
data.forEach((element) => {
    d3.select("#"+element.id)
    .attr("data-bs-toggle", "tooltip")
    .attr("title", element.excerpt)
    .attr("class", "tt");
})