[{"source":"Erwin Parviz","target":"Paul Reed"},
{"source":"Erwin Parviz","target":"Hugh Conroy"},
{"source":"Erwin Parviz","target":"Alistair Webster"},
{"source":"Erwin Parviz","target":"Dominic Wallace"},
{"source":"Erwin Parviz","target":"Susan Grbic"},
{"source":"Erwin Parviz","target":"Steven Henger"},
{"source":"Erwin Parviz","target":"Rachel Short"},
{"source":"Erwin Parviz","target":"Jean Louis Lafforgue"},
{"source":"Erwin Parviz","target":"Paolo Mammola"},
{"source":"Erwin Parviz","target":"Jonathan Dean Asher"},
{"source":"Erwin Parviz","target":"David Minarik"},
{"source":"Erwin Parviz","target":"Donald Bendernagel"},
{"source":"Erwin Parviz","target":"Julie Wan"},
{"source":"Erwin Parviz","target":"David Arnold"}]